// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./oci-client.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-android-arm64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-android-arm64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./oci-client.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-android-arm-eabi')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-android-arm-eabi/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if (process.config?.variables?.shlib_suffix === 'dll.a' || process.config?.variables?.node_target_type === 'shared_library') {
        try {
        return require('./oci-client.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-win32-x64-gnu')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-win32-x64-gnu/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./oci-client.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-win32-x64-msvc')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-win32-x64-msvc/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./oci-client.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-win32-ia32-msvc')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-win32-ia32-msvc/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./oci-client.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-win32-arm64-msvc')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-win32-arm64-msvc/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./oci-client.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    try {
      const binding = require('@dfatwork-pkgs/oci-client-darwin-universal')
      const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-darwin-universal/package.json').version
      if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
        throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
      }
      return binding
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./oci-client.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-darwin-x64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-darwin-x64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./oci-client.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-darwin-arm64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-darwin-arm64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./oci-client.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-freebsd-x64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-freebsd-x64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./oci-client.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-freebsd-arm64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-freebsd-arm64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./oci-client.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-x64-musl')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-x64-musl/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./oci-client.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-x64-gnu')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-x64-gnu/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./oci-client.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-arm64-musl')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-arm64-musl/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./oci-client.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-arm64-gnu')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-arm64-gnu/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./oci-client.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-arm-musleabihf')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-arm-musleabihf/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./oci-client.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-arm-gnueabihf')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-arm-gnueabihf/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./oci-client.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-loong64-musl')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-loong64-musl/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./oci-client.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-loong64-gnu')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-loong64-gnu/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./oci-client.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-riscv64-musl')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-riscv64-musl/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./oci-client.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
        try {
          const binding = require('@dfatwork-pkgs/oci-client-linux-riscv64-gnu')
          const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-riscv64-gnu/package.json').version
          if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
            throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
          }
          return binding
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./oci-client.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-linux-ppc64-gnu')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-ppc64-gnu/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./oci-client.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-linux-s390x-gnu')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-linux-s390x-gnu/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./oci-client.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-openharmony-arm64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-openharmony-arm64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./oci-client.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-openharmony-x64')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-openharmony-x64/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./oci-client.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        const binding = require('@dfatwork-pkgs/oci-client-openharmony-arm')
        const bindingPackageVersion = require('@dfatwork-pkgs/oci-client-openharmony-arm/package.json').version
        if (bindingPackageVersion !== '0.15.0' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK && process.env.NAPI_RS_ENFORCE_VERSION_CHECK !== '0') {
          throw new Error(`Native binding package version mismatch, expected 0.15.0 but got ${bindingPackageVersion}. You can reinstall dependencies to fix this issue.`)
        }
        return binding
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  let wasiBinding = null
  let wasiBindingError = null
  try {
    wasiBinding = require('./oci-client.wasi.cjs')
    nativeBinding = wasiBinding
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      wasiBindingError = err
    }
  }
  if (!nativeBinding) {
    try {
      wasiBinding = require('@dfatwork-pkgs/oci-client-wasm32-wasi')
      nativeBinding = wasiBinding
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        wasiBindingError.cause = err
        loadErrors.push(err)
      }
    }
  }
  if (process.env.NAPI_RS_FORCE_WASI === 'error' && !wasiBinding) {
    const error = new Error('WASI binding not found and NAPI_RS_FORCE_WASI is set to error')
    error.cause = wasiBindingError
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      {
        cause: loadErrors.reduce((err, cur) => {
          cur.cause = err
          return cur
        }),
      },
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.OciClient = nativeBinding.OciClient
module.exports.anonymousAuth = nativeBinding.anonymousAuth
module.exports.basicAuth = nativeBinding.basicAuth
module.exports.bearerAuth = nativeBinding.bearerAuth
module.exports.CertificateEncoding = nativeBinding.CertificateEncoding
module.exports.ClientProtocol = nativeBinding.ClientProtocol
module.exports.IMAGE_CONFIG_MEDIA_TYPE = nativeBinding.IMAGE_CONFIG_MEDIA_TYPE
module.exports.IMAGE_DOCKER_CONFIG_MEDIA_TYPE = nativeBinding.IMAGE_DOCKER_CONFIG_MEDIA_TYPE
module.exports.IMAGE_DOCKER_LAYER_GZIP_MEDIA_TYPE = nativeBinding.IMAGE_DOCKER_LAYER_GZIP_MEDIA_TYPE
module.exports.IMAGE_DOCKER_LAYER_TAR_MEDIA_TYPE = nativeBinding.IMAGE_DOCKER_LAYER_TAR_MEDIA_TYPE
module.exports.IMAGE_LAYER_GZIP_MEDIA_TYPE = nativeBinding.IMAGE_LAYER_GZIP_MEDIA_TYPE
module.exports.IMAGE_LAYER_MEDIA_TYPE = nativeBinding.IMAGE_LAYER_MEDIA_TYPE
module.exports.IMAGE_LAYER_NONDISTRIBUTABLE_GZIP_MEDIA_TYPE = nativeBinding.IMAGE_LAYER_NONDISTRIBUTABLE_GZIP_MEDIA_TYPE
module.exports.IMAGE_LAYER_NONDISTRIBUTABLE_MEDIA_TYPE = nativeBinding.IMAGE_LAYER_NONDISTRIBUTABLE_MEDIA_TYPE
module.exports.IMAGE_MANIFEST_LIST_MEDIA_TYPE = nativeBinding.IMAGE_MANIFEST_LIST_MEDIA_TYPE
module.exports.IMAGE_MANIFEST_MEDIA_TYPE = nativeBinding.IMAGE_MANIFEST_MEDIA_TYPE
module.exports.ManifestType = nativeBinding.ManifestType
module.exports.OCI_IMAGE_INDEX_MEDIA_TYPE = nativeBinding.OCI_IMAGE_INDEX_MEDIA_TYPE
module.exports.OCI_IMAGE_MEDIA_TYPE = nativeBinding.OCI_IMAGE_MEDIA_TYPE
module.exports.ORG_OPENCONTAINERS_IMAGE_AUTHORS = nativeBinding.ORG_OPENCONTAINERS_IMAGE_AUTHORS
module.exports.ORG_OPENCONTAINERS_IMAGE_BASE_DIGEST = nativeBinding.ORG_OPENCONTAINERS_IMAGE_BASE_DIGEST
module.exports.ORG_OPENCONTAINERS_IMAGE_BASE_NAME = nativeBinding.ORG_OPENCONTAINERS_IMAGE_BASE_NAME
module.exports.ORG_OPENCONTAINERS_IMAGE_CREATED = nativeBinding.ORG_OPENCONTAINERS_IMAGE_CREATED
module.exports.ORG_OPENCONTAINERS_IMAGE_DESCRIPTION = nativeBinding.ORG_OPENCONTAINERS_IMAGE_DESCRIPTION
module.exports.ORG_OPENCONTAINERS_IMAGE_DOCUMENTATION = nativeBinding.ORG_OPENCONTAINERS_IMAGE_DOCUMENTATION
module.exports.ORG_OPENCONTAINERS_IMAGE_LICENSES = nativeBinding.ORG_OPENCONTAINERS_IMAGE_LICENSES
module.exports.ORG_OPENCONTAINERS_IMAGE_REF_NAME = nativeBinding.ORG_OPENCONTAINERS_IMAGE_REF_NAME
module.exports.ORG_OPENCONTAINERS_IMAGE_REVISION = nativeBinding.ORG_OPENCONTAINERS_IMAGE_REVISION
module.exports.ORG_OPENCONTAINERS_IMAGE_SOURCE = nativeBinding.ORG_OPENCONTAINERS_IMAGE_SOURCE
module.exports.ORG_OPENCONTAINERS_IMAGE_TITLE = nativeBinding.ORG_OPENCONTAINERS_IMAGE_TITLE
module.exports.ORG_OPENCONTAINERS_IMAGE_URL = nativeBinding.ORG_OPENCONTAINERS_IMAGE_URL
module.exports.ORG_OPENCONTAINERS_IMAGE_VENDOR = nativeBinding.ORG_OPENCONTAINERS_IMAGE_VENDOR
module.exports.ORG_OPENCONTAINERS_IMAGE_VERSION = nativeBinding.ORG_OPENCONTAINERS_IMAGE_VERSION
module.exports.RegistryAuthType = nativeBinding.RegistryAuthType
module.exports.WASM_CONFIG_MEDIA_TYPE = nativeBinding.WASM_CONFIG_MEDIA_TYPE
module.exports.WASM_LAYER_MEDIA_TYPE = nativeBinding.WASM_LAYER_MEDIA_TYPE
